# Generated by Django 3.2.3 on 2021-06-07 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('precio_producto', models.SmallIntegerField(verbose_name='Precio del producto')),
                ('codigo_barra', models.CharField(max_length=150, verbose_name='Codigo de barra')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categoria.categoria')),
            ],
        ),
    ]
